-- V2__create_service_requests_table.sql

-- Cria a tabela service_requests
CREATE TABLE service_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(255) NOT NULL, -- Mapeado de ServiceCategory (ENUM em Java, armazenado como String)
    location VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,   -- Mapeado de ServiceStatus (ENUM em Java, armazenado como String)
    client_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_service_requests PRIMARY KEY (id)
);

-- Adiciona a chave estrangeira para a tabela users
-- Presume-se que a tabela 'users' já existe e tem uma coluna 'id' como chave primária.
ALTER TABLE service_requests
ADD CONSTRAINT fk_service_requests_on_client FOREIGN KEY (client_id) REFERENCES users (id);

-- Opcional: Adicionar índices para otimização de consultas comuns
CREATE INDEX idx_service_requests_client_id ON service_requests (client_id);
CREATE INDEX idx_service_requests_status ON service_requests (status);
CREATE INDEX idx_service_requests_category ON service_requests (category);